name = "instacodesms-simple"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[dev]
port = 3000
local_protocol = "http"

# 配置 ESBuild 模块解析规则
[[rules]]
type = "ESModule"
globs = ["**/*.ts"]
fallthrough = true
