/**
 * 错误码常量
 * 用于 API 响应和日志记录
 */

export const ERROR_CODES = {
  // 参数验证
  INVALID_SERVICE: 'ERR_001',
  INVALID_QUANTITY: 'ERR_002',
  INVALID_PRICE: 'ERR_003',
  INVALID_ORDER_ID: 'ERR_004',

  // 支付相关
  PAYMENT_FAILED: 'ERR_101',
  PAYMENT_TIMEOUT: 'ERR_102',
  PAYMENT_CANCELLED: 'ERR_103',

  // 库存相关
  OUT_OF_STOCK: 'ERR_201',
  INSUFFICIENT_STOCK: 'ERR_202',

  // 上游相关
  UPSTREAM_ERROR: 'ERR_301',
  UPSTREAM_TIMEOUT: 'ERR_302',
  UPSTREAM_UNAVAILABLE: 'ERR_303',

  // 系统相关
  INTERNAL_ERROR: 'ERR_500',
  SERVICE_UNAVAILABLE: 'ERR_503',
} as const

export const ERROR_MESSAGES: Record<string, string> = {
  [ERROR_CODES.INVALID_SERVICE]: '请选择有效的服务项目',
  [ERROR_CODES.INVALID_QUANTITY]: '请输入有效的购买数量',
  [ERROR_CODES.INVALID_PRICE]: '价格计算错误',
  [ERROR_CODES.INVALID_ORDER_ID]: '订单号无效',

  [ERROR_CODES.PAYMENT_FAILED]: '支付失败，请重试',
  [ERROR_CODES.PAYMENT_TIMEOUT]: '支付超时，请重试',
  [ERROR_CODES.PAYMENT_CANCELLED]: '支付已取消',

  [ERROR_CODES.OUT_OF_STOCK]: '商品已售罄',
  [ERROR_CODES.INSUFFICIENT_STOCK]: '库存不足',

  [ERROR_CODES.UPSTREAM_ERROR]: '上游服务返回错误',
  [ERROR_CODES.UPSTREAM_TIMEOUT]: '上游服务响应超时',
  [ERROR_CODES.UPSTREAM_UNAVAILABLE]: '上游服务暂时不可用',

  [ERROR_CODES.INTERNAL_ERROR]: '服务器内部错误',
  [ERROR_CODES.SERVICE_UNAVAILABLE]: '服务暂时不可用',
}
